// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw_H4MaVtTu9JbDtHFz_PWzS_13RCyS2Y',
    appId: '1:1034973456570:web:f21c94860d60cc21a17a83',
    messagingSenderId: '1034973456570',
    projectId: 'chat-4411b',
    authDomain: 'chat-4411b.firebaseapp.com',
    storageBucket: 'chat-4411b.appspot.com',
    measurementId: 'G-Q4R06K41JV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5GFp5HW6jg0n-qpOB0bdhRhUwMYmbVaA',
    appId: '1:1034973456570:android:b5e020e52ef0e62ca17a83',
    messagingSenderId: '1034973456570',
    projectId: 'chat-4411b',
    storageBucket: 'chat-4411b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjmYOY7C3hFF0FD0ZO3M3i85LJPb9ohu4',
    appId: '1:1034973456570:ios:ab69029f94fbf625a17a83',
    messagingSenderId: '1034973456570',
    projectId: 'chat-4411b',
    storageBucket: 'chat-4411b.appspot.com',
    iosClientId: '1034973456570-qvvvm7tcql7mc3jrgddlsl723dfjgmau.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
